service: app

provider:
    name: aws
    region: us-east-1

plugins:
    - ./vendor/bref/bref

functions:
    timezones:
        handler: timezones.php
        runtime: php-82
        timeout: 300
        events:
            - schedule: rate(5 minutes)

    flickr:
        handler: flickr.php
        runtime: php-82
        timeout: 300
        events:
            - schedule: rate(30 minutes)

    unsplash:
        handler: unsplash.php
        runtime: php-82
        timeout: 60
        events:
            - schedule: rate(1 hour)

    getutc:
        handler: getutc.php
        runtime: php-82
        events:
            - httpApi: 'GET /getutc'
            - schedule:
                rate: rate(5 minutes)
                input:
                    warmer: true

    uploadimage:
        handler: uploadimage.php
        runtime: php-82
        events:
            - httpApi: 'POST /uploadimage'

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
