service: app

provider:
    name: aws
    region: us-east-1

plugins:
    - ./vendor/bref/bref

functions:
    timezones:
        handler: timezones.php
        description: ''
        runtime: php-82
        timeout: 300
        events:
            - schedule: rate(5 minutes)

    flickr:
        handler: flickr.php
        description: ''
        runtime: php-82
        timeout: 300
        events:
            - schedule: rate(30 minutes)

    unsplash:
        handler: unsplash.php
        description: ''
        runtime: php-82
        timeout: 60
        events:
            - schedule: rate(1 hour)

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
